name: "spec"

on: [push, pull_request]

jobs:
  # this runs the tests in the docker image against live sqlite and openresty
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: build
        run: docker build -t pagesix-test .

      - name: test
        run: docker run pagesix-test

  # this runs all generic lua tests
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.4", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@master

      - name: build
        run: |
          [[ "${{ matrix.luaVersion }}" =~ ^5\.[12]$ ]] && luarocks install luabitop || true
          luarocks install busted
          luarocks install moonscript
          luarocks install tableshape
          luarocks install lsqlite3
          luarocks make

      - name: test
        run: |
          busted -o utfTerminal -v
